name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Micromamba ${{ matrix.python-version }}
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: TEST
          init-shell: bash
          create-args: >-
            python=${{ matrix.python-version }} pip
            --file requirements.txt
            --file requirements-dev.txt
            --channel conda-forge

      - name: Install xpublish-wms
        shell: bash -l {0}
        run: >
          python -m pip install -e . --no-deps --force-reinstall
          && micromamba info
          && micromamba list

      - name: Tests
        shell: bash -l {0}
        run: |
          python -m pytest -rxs --cov=xpublish_wms tests
